-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 14:44:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema magazijn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema magazijn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `magazijn` DEFAULT CHARACTER SET utf8 ;
USE `magazijn` ;

-- -----------------------------------------------------
-- Table `magazijn`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `magazijn`.`Category` ;

CREATE TABLE IF NOT EXISTS `magazijn`.`Category` (
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category`),
  CONSTRAINT `fk_Artikel_Category`
    FOREIGN KEY ()
    REFERENCES `magazijn`.`Category` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magazijn`.`Artikel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `magazijn`.`Artikel` ;

CREATE TABLE IF NOT EXISTS `magazijn`.`Artikel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `omschrijving` VARCHAR(45) NOT NULL,
  `aantal` INT NOT NULL,
  `inkoopprijs` FLOAT NOT NULL,
  `categorie` VARCHAR(45) NOT NULL,
  `goedgekeurd` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_Artikel_Category_idx` (`categorie` ASC),
  CONSTRAINT `fk_Artikel_Category`
    FOREIGN KEY (`categorie`)
    REFERENCES `magazijn`.`Category` (`category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `magazijn`.`Category`
-- -----------------------------------------------------
START TRANSACTION;
USE `magazijn`;
INSERT INTO `magazijn`.`Category` (`category`) VALUES ('Monitoren');
INSERT INTO `magazijn`.`Category` (`category`) VALUES ('Netwerkapparaturen');
INSERT INTO `magazijn`.`Category` (`category`) VALUES ('Kabels');

COMMIT;

